const passport = require('passport')
const GoogleStrategy = require('passport-google-oauth20').Strategy
const mongoose = require('mongoose')
const keys = require('../config/keys')

// fetches the model class out of mongoose
const User = mongoose.model('users')

passport.serializeUser((user, done) => {
    // user.id is shortcut to user._id.$oid which is a unique identifier automatically generated by mongo
    // user.id is different from the googleId
    done(null, user.id)
})

passport.deserializeUser((id, done) => {
    User.findById(id)
        .then(user => {
            done(null, user)
        })
})

passport.use(
    new GoogleStrategy(
    {
        clientID: keys.googleClientID,
        clientSecret: keys.googleClientSecret,
        callbackURL: '/auth/google/callback',
        proxy: true
    }, 
    async (accessToken, refreshToken, profile, done) => {
        
        const existingUser = await User.findOne({googleId: profile.id})

        if (existingUser) {
            done(null, existingUser)
        } else {
            const user = await new User({ googleId: profile.id }).save()
            done(null, user)
        }
    })
)
